title: GSoC'26 Blogs
description: >- 
  A blog series of my Gsoc journey.
baseurl: "" 
url: "http://bhargav-j47.github.io/" 

remote_theme: jekyll/minima
minima:
  skin: dark
# Build settings
markdown: kramdown
